// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCurrentYearWatcherInterface is an autogenerated mock type for the CurrentYearWatcherInterface type
type MockCurrentYearWatcherInterface struct {
	mock.Mock
}

// execute provides a mock function with given fields: _a0
func (_m *MockCurrentYearWatcherInterface) execute(_a0 context.Context) {
	_m.Called(_a0)
}

// getYear provides a mock function with given fields:
func (_m *MockCurrentYearWatcherInterface) getYear() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewMockCurrentYearWatcherInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCurrentYearWatcherInterface creates a new instance of MockCurrentYearWatcherInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCurrentYearWatcherInterface(t mockConstructorTestingTNewMockCurrentYearWatcherInterface) *MockCurrentYearWatcherInterface {
	mock := &MockCurrentYearWatcherInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
