// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"
	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdatedScoresImporterInterface is an autogenerated mock type for the UpdatedScoresImporterInterface type
type MockUpdatedScoresImporterInterface struct {
	mock.Mock
}

// addEvent provides a mock function with given fields: event
func (_m *MockUpdatedScoresImporterInterface) addEvent(event dekanatEvents.ScoreEditEvent) {
	_m.Called(event)
}

// execute provides a mock function with given fields: _a0
func (_m *MockUpdatedScoresImporterInterface) execute(_a0 context.Context) {
	_m.Called(_a0)
}

// getConfirmed provides a mock function with given fields:
func (_m *MockUpdatedScoresImporterInterface) getConfirmed() <-chan dekanatEvents.ScoreEditEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.ScoreEditEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.ScoreEditEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.ScoreEditEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockUpdatedScoresImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUpdatedScoresImporterInterface creates a new instance of MockUpdatedScoresImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUpdatedScoresImporterInterface(t mockConstructorTestingTNewMockUpdatedScoresImporterInterface) *MockUpdatedScoresImporterInterface {
	mock := &MockUpdatedScoresImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
