// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"
	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"

	mock "github.com/stretchr/testify/mock"
)

// MockDeletedScoresImporterInterface is an autogenerated mock type for the DeletedScoresImporterInterface type
type MockDeletedScoresImporterInterface struct {
	mock.Mock
}

// addEvent provides a mock function with given fields: event
func (_m *MockDeletedScoresImporterInterface) addEvent(event dekanatEvents.LessonDeletedEvent) {
	_m.Called(event)
}

// execute provides a mock function with given fields: _a0
func (_m *MockDeletedScoresImporterInterface) execute(_a0 context.Context) {
	_m.Called(_a0)
}

// getConfirmed provides a mock function with given fields:
func (_m *MockDeletedScoresImporterInterface) getConfirmed() <-chan dekanatEvents.LessonDeletedEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.LessonDeletedEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.LessonDeletedEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.LessonDeletedEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockDeletedScoresImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDeletedScoresImporterInterface creates a new instance of MockDeletedScoresImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDeletedScoresImporterInterface(t mockConstructorTestingTNewMockDeletedScoresImporterInterface) *MockDeletedScoresImporterInterface {
	mock := &MockDeletedScoresImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
