// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"
	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"

	mock "github.com/stretchr/testify/mock"
)

// MockCreatedLessonsImporterInterface is an autogenerated mock type for the CreatedLessonsImporterInterface type
type MockCreatedLessonsImporterInterface struct {
	mock.Mock
}

// addEvent provides a mock function with given fields: event
func (_m *MockCreatedLessonsImporterInterface) addEvent(event dekanatEvents.LessonCreateEvent) {
	_m.Called(event)
}

// execute provides a mock function with given fields: _a0
func (_m *MockCreatedLessonsImporterInterface) execute(_a0 context.Context) {
	_m.Called(_a0)
}

// getConfirmed provides a mock function with given fields:
func (_m *MockCreatedLessonsImporterInterface) getConfirmed() <-chan dekanatEvents.LessonCreateEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.LessonCreateEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.LessonCreateEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.LessonCreateEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockCreatedLessonsImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCreatedLessonsImporterInterface creates a new instance of MockCreatedLessonsImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCreatedLessonsImporterInterface(t mockConstructorTestingTNewMockCreatedLessonsImporterInterface) *MockCreatedLessonsImporterInterface {
	mock := &MockCreatedLessonsImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
