// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventDeleterInterface is an autogenerated mock type for the EventDeleterInterface type
type MockEventDeleterInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: event
func (_m *MockEventDeleterInterface) Delete(event interface{}) {
	_m.Called(event)
}

// execute provides a mock function with given fields: ctx
func (_m *MockEventDeleterInterface) execute(ctx context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewMockEventDeleterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEventDeleterInterface creates a new instance of MockEventDeleterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEventDeleterInterface(t mockConstructorTestingTNewMockEventDeleterInterface) *MockEventDeleterInterface {
	mock := &MockEventDeleterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
