// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"
	mock "github.com/stretchr/testify/mock"
)

// CreatedLessonsImporterInterface is an autogenerated mock type for the CreatedLessonsImporterInterface type
type CreatedLessonsImporterInterface struct {
	mock.Mock
}

// AddEvent provides a mock function with given fields: event
func (_m *CreatedLessonsImporterInterface) AddEvent(event dekanatEvents.LessonCreateEvent) {
	_m.Called(event)
}

// Execute provides a mock function with given fields: _a0
func (_m *CreatedLessonsImporterInterface) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// GetConfirmed provides a mock function with given fields:
func (_m *CreatedLessonsImporterInterface) GetConfirmed() <-chan dekanatEvents.LessonCreateEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.LessonCreateEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.LessonCreateEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.LessonCreateEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewCreatedLessonsImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreatedLessonsImporterInterface creates a new instance of CreatedLessonsImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreatedLessonsImporterInterface(t mockConstructorTestingTNewCreatedLessonsImporterInterface) *CreatedLessonsImporterInterface {
	mock := &CreatedLessonsImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
