// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CurrentYearWatcherInterface is an autogenerated mock type for the CurrentYearWatcherInterface type
type CurrentYearWatcherInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CurrentYearWatcherInterface) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// GetYear provides a mock function with given fields:
func (_m *CurrentYearWatcherInterface) GetYear() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewCurrentYearWatcherInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrentYearWatcherInterface creates a new instance of CurrentYearWatcherInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrentYearWatcherInterface(t mockConstructorTestingTNewCurrentYearWatcherInterface) *CurrentYearWatcherInterface {
	mock := &CurrentYearWatcherInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
