// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrentYearGetterInterface is an autogenerated mock type for the CurrentYearGetterInterface type
type CurrentYearGetterInterface struct {
	mock.Mock
}

// GetYear provides a mock function with given fields:
func (_m *CurrentYearGetterInterface) GetYear() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewCurrentYearGetterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrentYearGetterInterface creates a new instance of CurrentYearGetterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrentYearGetterInterface(t mockConstructorTestingTNewCurrentYearGetterInterface) *CurrentYearGetterInterface {
	mock := &CurrentYearGetterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
