// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"
	mock "github.com/stretchr/testify/mock"
)

// DeletedScoresImporterInterface is an autogenerated mock type for the DeletedScoresImporterInterface type
type DeletedScoresImporterInterface struct {
	mock.Mock
}

// AddEvent provides a mock function with given fields: event
func (_m *DeletedScoresImporterInterface) AddEvent(event dekanatEvents.LessonDeletedEvent) {
	_m.Called(event)
}

// Execute provides a mock function with given fields: _a0
func (_m *DeletedScoresImporterInterface) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// GetConfirmed provides a mock function with given fields:
func (_m *DeletedScoresImporterInterface) GetConfirmed() <-chan dekanatEvents.LessonDeletedEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.LessonDeletedEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.LessonDeletedEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.LessonDeletedEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewDeletedScoresImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeletedScoresImporterInterface creates a new instance of DeletedScoresImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeletedScoresImporterInterface(t mockConstructorTestingTNewDeletedScoresImporterInterface) *DeletedScoresImporterInterface {
	mock := &DeletedScoresImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
