// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"
	mock "github.com/stretchr/testify/mock"
)

// EditedLessonsImporterInterface is an autogenerated mock type for the EditedLessonsImporterInterface type
type EditedLessonsImporterInterface struct {
	mock.Mock
}

// AddEvent provides a mock function with given fields: event
func (_m *EditedLessonsImporterInterface) AddEvent(event dekanatEvents.LessonEditEvent) {
	_m.Called(event)
}

// Execute provides a mock function with given fields: _a0
func (_m *EditedLessonsImporterInterface) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// GetConfirmed provides a mock function with given fields:
func (_m *EditedLessonsImporterInterface) GetConfirmed() <-chan dekanatEvents.LessonEditEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.LessonEditEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.LessonEditEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.LessonEditEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewEditedLessonsImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewEditedLessonsImporterInterface creates a new instance of EditedLessonsImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEditedLessonsImporterInterface(t mockConstructorTestingTNewEditedLessonsImporterInterface) *EditedLessonsImporterInterface {
	mock := &EditedLessonsImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
