// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EventDeleterInterface is an autogenerated mock type for the EventDeleterInterface type
type EventDeleterInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: event
func (_m *EventDeleterInterface) Delete(event interface{}) {
	_m.Called(event)
}

// Execute provides a mock function with given fields: ctx
func (_m *EventDeleterInterface) Execute(ctx context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewEventDeleterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventDeleterInterface creates a new instance of EventDeleterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventDeleterInterface(t mockConstructorTestingTNewEventDeleterInterface) *EventDeleterInterface {
	mock := &EventDeleterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
