// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MaxLessonIdGetterInterface is an autogenerated mock type for the MaxLessonIdGetterInterface type
type MaxLessonIdGetterInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MaxLessonIdGetterInterface) Get() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

type mockConstructorTestingTNewMaxLessonIdGetterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMaxLessonIdGetterInterface creates a new instance of MaxLessonIdGetterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMaxLessonIdGetterInterface(t mockConstructorTestingTNewMaxLessonIdGetterInterface) *MaxLessonIdGetterInterface {
	mock := &MaxLessonIdGetterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
