// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MaxLessonIdSetterInterface is an autogenerated mock type for the MaxLessonIdSetterInterface type
type MaxLessonIdSetterInterface struct {
	mock.Mock
}

// Set provides a mock function with given fields: _a0
func (_m *MaxLessonIdSetterInterface) Set(_a0 uint) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewMaxLessonIdSetterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMaxLessonIdSetterInterface creates a new instance of MaxLessonIdSetterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMaxLessonIdSetterInterface(t mockConstructorTestingTNewMaxLessonIdSetterInterface) *MaxLessonIdSetterInterface {
	mock := &MaxLessonIdSetterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
