// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	dekanatEvents "github.com/kneu-messenger-pigeon/dekanat-events"
	mock "github.com/stretchr/testify/mock"
)

// UpdatedScoresImporterInterface is an autogenerated mock type for the UpdatedScoresImporterInterface type
type UpdatedScoresImporterInterface struct {
	mock.Mock
}

// AddEvent provides a mock function with given fields: event
func (_m *UpdatedScoresImporterInterface) AddEvent(event dekanatEvents.ScoreEditEvent) {
	_m.Called(event)
}

// Execute provides a mock function with given fields: _a0
func (_m *UpdatedScoresImporterInterface) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// GetConfirmed provides a mock function with given fields:
func (_m *UpdatedScoresImporterInterface) GetConfirmed() <-chan dekanatEvents.ScoreEditEvent {
	ret := _m.Called()

	var r0 <-chan dekanatEvents.ScoreEditEvent
	if rf, ok := ret.Get(0).(func() <-chan dekanatEvents.ScoreEditEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan dekanatEvents.ScoreEditEvent)
		}
	}

	return r0
}

type mockConstructorTestingTNewUpdatedScoresImporterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdatedScoresImporterInterface creates a new instance of UpdatedScoresImporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdatedScoresImporterInterface(t mockConstructorTestingTNewUpdatedScoresImporterInterface) *UpdatedScoresImporterInterface {
	mock := &UpdatedScoresImporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
