name: Run test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    permissions:
      contents: read
    uses: kneu-messenger-pigeon/github-workflows/.github/workflows/release.yaml@main
    with:
      skip_build: true
